CREATE TABLE "MYUSER"."STOCKS"
   (	"SYMBOL" CHAR(4 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"MARKET_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "MYUSER"."STOCKS" ADD PRIMARY KEY ("SYMBOL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

   COMMENT ON TABLE "MYUSER"."STOCKS"  IS 'Information about stocks such as symbol and description of company and sector';

INSERT INTO "MYUSER"."STOCKS" ("SYMBOL","DESCRIPTION","MARKET_PRICE")
VALUES ('ACME','Tech company. Also involved in supplying Wile E Coyote',127.35);

INSERT INTO "MYUSER"."STOCKS" ("SYMBOL","DESCRIPTION","MARKET_PRICE")
VALUES ('ZENO','Tech company specializing in AI and spatial',289.75);

INSERT INTO "MYUSER"."STOCKS" ("SYMBOL","DESCRIPTION","MARKET_PRICE")
VALUES ('TRAK','TrakSmart Logistics',58.60);

INSERT INTO "MYUSER"."STOCKS" ("SYMBOL","DESCRIPTION","MARKET_PRICE")
VALUES ('QBIT','Qbit Quantum Systems',215.90);

INSERT INTO "MYUSER"."STOCKS" ("SYMBOL","DESCRIPTION","MARKET_PRICE")
VALUES ('NOVA','Nova Aerospace Technologies',412.40);

COMMIT;





CREATE TABLE "MYUSER"."PORTFOLIO"
   (	"ACCOUNT_ID" NUMBER,
	"SYMBOL" CHAR(4 BYTE),
	"SHARES" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "MYUSER"."PORTFOLIO" ADD CONSTRAINT "FK_PORTFOLIO_STOCK" FOREIGN KEY ("SYMBOL")
	  REFERENCES "MYUSER"."STOCKS" ("SYMBOL") ENABLE;

   COMMENT ON TABLE "MYUSER"."PORTFOLIO"  IS 'Information about stocks owned in portfolio including the count and current market price';

INSERT INTO "MYUSER"."PORTFOLIO" ("ACCOUNT_ID","SYMBOL","SHARES")
VALUES (101,'ACME',59);

INSERT INTO "MYUSER"."PORTFOLIO" ("ACCOUNT_ID","SYMBOL","SHARES")
VALUES (101,'NOVA',23);

INSERT INTO "MYUSER"."PORTFOLIO" ("ACCOUNT_ID","SYMBOL","SHARES")
VALUES (101,'QBIT',89);

INSERT INTO "MYUSER"."PORTFOLIO" ("ACCOUNT_ID","SYMBOL","SHARES")
VALUES (101,'TRAK',76);

INSERT INTO "MYUSER"."PORTFOLIO" ("ACCOUNT_ID","SYMBOL","SHARES")
VALUES (101,'ZENO',34);

COMMIT;





CREATE OR REPLACE FORCE EDITIONABLE VIEW "MYUSER"."PORTFOLIO_STOCKS" ("ACCOUNT_ID", "SYMBOL", "SHARES", "DESCRIPTION", "MARKET_PRICE") AS
  SELECT p.account_id, p.symbol, p.shares, s.description, s.market_price FROM portfolio p JOIN stocks s ON p.symbol = s.symbol;

   COMMENT ON TABLE "MYUSER"."PORTFOLIO_STOCKS"  IS 'Information about stocks owned in portfolio including the count and current market price and information about stock such as symbol and description of company and sector';



 CREATE TABLE "MYUSER"."PDFCOLLECTION"
    (	"ID" VARCHAR2(4000 BYTE),
 	"TEXT" VARCHAR2(4000 BYTE),
 	"METADATA" VARCHAR2(4000 BYTE),
 	"EMBEDDING" VECTOR
    ) SEGMENT CREATION IMMEDIATE
   PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
  NOCOMPRESS LOGGING
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "DATA"
  VECTOR ("EMBEDDING") STORE AS (
   TABLESPACE "DATA"  CHUNK 8192 RETENTION MIN 1800
   STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0
   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 ALTER TABLE "MYUSER"."PDFCOLLECTION" ADD PRIMARY KEY ("ID")
   USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 167 COMPUTE STATISTICS
   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   TABLESPACE "DATA"  ENABLE;


